name: Check CFITSIO release

on:
  schedule:
    # Weekly Monday 6 AM build.
    # * is a special character in YAML so you have to quote this string.
    - cron: '28 14 * * 1'

jobs:
  check_cfitsio:
    name: Open issue if new release found
    runs-on: ubuntu-latest
    steps:
    - name: Check release
      uses: pllim/actions-check_cfitsio_release@main
      env:
        CTX_EVENT: ${{ github.event }}
        CFITSIO_CHECK_N_DAYS: 7
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
