name: Check CFITSIO release

on:
  schedule:
    # Weekly Tuesday 6 AM build.
    # * is a special character in YAML so you have to quote this string.
    - cron: '0 6 * * 2'
  push:

jobs:
  check_cfitsio:
    name: Open issue if new release found
    runs-on: ubuntu-latest
    steps:
    - name: Check release
      uses: pllim/actions-check_cfitsio_release@ts-action
      with:
        CFITSIO_CHECK_N_DAYS: 300
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
