name: CI

on:
  pull_request:

jobs:
  # This is placeholder for your real tests.
  tests:
    name: This should not run if skipped
    runs-on: ubuntu-latest
    steps:
    - name: You shall not pass
      run: echo "Here"
