name: whoami

on:
  push:

jobs:
  showme:
    runs-on: ubuntu-latest
    steps:
    #- name: github
    #  env:
    #    CTX_GITHUB: ${{ toJson(github) }}
    #  run: echo $CTX_GITHUB
    - name: runner
      env:
        CTX_RUNNER: ${{ toJson(runner) }}
        MY_OS: ${{ runner.os }}
      run: |
        echo $CTX_RUNNER
        echo $MY_OS
    #- name: job
    #  env:
    #    CTX_JOB: ${{ toJson(job) }}
    #  run: echo $CTX_JOB
