name: whoami

on:
  push:

jobs:
  showme:
    runs-on: ubuntu-latest
    steps:
    - name: github
      env:
        CTX_GITHUB: ${{ toJson(github) }}
      run: echo $CTX_GITHUB
    - name: env
      env:
        CTX_ENV: ${{ toJson(env) }}
      run: echo $CTX_ENV
    - name: job
      env:
        CTX_JOB: ${{ toJson(job) }}
      run: echo $CTX_JOB
