name: whoami

on:
  push:
  schedule:
    # Weekly Monday 6 AM build.
    # * is a special character in YAML so you have to quote this string.
    - cron: '15 22 * * 1'

jobs:
  showme:
    runs-on: ubuntu-latest
    # COMMENT OUT TO ENABLE
    if: github.repository == 'astropy/astropy'
    steps:
    - name: github
      env:
        CTX_GITHUB: ${{ toJson(github) }}
        CTX_EVENT: ${{ toJson(github.event) }}
      run: |
        echo $CTX_GITHUB
        echo $CTX_EVENT
    - name: runner
      env:
        CTX_RUNNER: ${{ toJson(runner) }}
        MY_OS: ${{ runner.os }}
      run: |
        echo $CTX_RUNNER
        echo $MY_OS
    #- name: job
    #  env:
    #    CTX_JOB: ${{ toJson(job) }}
    #  run: echo $CTX_JOB
